version: 2.1
jobs:
  test:
    docker:
      - image: jacopoventurin/mlcg_prebuilt_cpu_python_312:v0.1
    parallelism: 1   # run tests across 1 parallel containers
    steps:
      - checkout
      - run:
          name: "Install repo"
          command: |
            pip --version
            pip install .[dev]
      - run:
          name: "Run code tests"
          command: "pytest ."

workflows:
  version: 2
  build_and_test:
    jobs:
      - test